In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,r2_score,confusion_matrix,classification_report,mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris=load_iris()

# Convert into DataFrame
df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
X,y = iris.data,iris.target

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.3,random_state=42
)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [3]:
log_model=LogisticRegression()
log_model.fit(X_train_scaled,y_train)
y_pred=log_model.predict(X_test_scaled)

In [4]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average="weighted"))
print("Recall:", recall_score(y_test, y_pred, average="weighted"))
print("F1 Score:", f1_score(y_test, y_pred, average="weighted"))

print("confusion matrix",confusion_matrix(y_test,y_pred))
print("classification_report",classification_report(y_test,y_pred))


Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
confusion matrix [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [5]:
#Naive Bayes
nb_model=GaussianNB()
nb_model.fit(X_train_scaled,y_train)
y_pred=nb_model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average="weighted"))
print("Recall:", recall_score(y_test, y_pred, average="weighted"))
print("F1 Score:", f1_score(y_test, y_pred, average="weighted"))

print("confusion matrix",confusion_matrix(y_test,y_pred))
print("classification_report",classification_report(y_test,y_pred))


Accuracy: 0.9777777777777777
Precision: 0.9793650793650793
Recall: 0.9777777777777777
F1 Score: 0.9777448559670782
confusion matrix [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [6]:
#kNN
knn_model=KNeighborsClassifier(n_neighbors=9)
knn_model.fit(X_train_scaled,y_train)
knn_pred=knn_model.predict(X_test_scaled)

print("KNN Accuracy:")
print(accuracy_score(y_test, knn_pred))

print(confusion_matrix(y_test, knn_pred))

print(classification_report(y_test, knn_pred))

KNN Accuracy:
1.0
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [7]:
linear_model = LinearRegression()

linear_model.fit(X_train_scaled, y_train)

linear_pred = linear_model.predict(X_test_scaled)

linear_pred = np.round(linear_pred)

linear_pred = np.clip(linear_pred, 0, 2)

linear_pred = linear_pred.astype(int)

print("Linear Regression Accuracy:")
print(accuracy_score(y_test, linear_pred))

print("MSE:", mean_squared_error(y_test, linear_pred))

print("R2 Score:", r2_score(y_test, linear_pred))

Linear Regression Accuracy:
1.0
MSE: 0.0
R2 Score: 1.0


In [8]:
classifier=KNeighborsClassifier()
param_grid={"n_neighbors":[3,5,7,9]}

classifierCV=GridSearchCV(
    classifier,
    param_grid,
    cv=5,
    scoring="accuracy"
)

classifierCV.fit(X_train_scaled,y_train)
y_pred=classifierCV.predict(X_test_scaled)

print("recall : ", recall_score(y_test, y_pred, average="weighted"))
print("accuracy : ", accuracy_score(y_test, y_pred))
print("precision : ", precision_score(y_test, y_pred, average="weighted"))

# Results
res = pd.DataFrame(classifierCV.cv_results_)
print(res)

recall :  1.0
accuracy :  1.0
precision :  1.0
   mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001880      0.000530         0.006197        0.001817   
1       0.001986      0.000588         0.006280        0.000278   
2       0.001658      0.000884         0.004172        0.002733   
3       0.001337      0.000880         0.003777        0.001243   

   param_n_neighbors              params  split0_test_score  \
0                  3  {'n_neighbors': 3}           0.952381   
1                  5  {'n_neighbors': 5}           0.904762   
2                  7  {'n_neighbors': 7}           0.952381   
3                  9  {'n_neighbors': 9}           0.952381   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.952381           0.857143                1.0           0.952381   
1           0.904762           0.857143                1.0           0.904762   
2           0.904762           0.857143                1.0