In [1]:
import numpy as np
import time

In [2]:
a=[1,2,3,4,5]  
print(type(a))

<class 'list'>


In [3]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))   

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#compare execution performance
# size=1_000_000
# py_list=list(range(size))
# start=time.time()
# sq_list=[x**2 for x in py_list]
# end=time.time()
# print(f"python list time ={end-start} seconds")
# np_arr=np.array(py_list)
# start=time.time()
# sq_arr=np_arr**2 # vectorization
# end=time.time()
# print(f"nimpy array time ={end-start} seconds")    


In [5]:
#memory comparison
# import sys
# print(f"python list size = {sys.getsizeof(py_list)*len(py_list)} bytes")
# print(f"numpy array size ={np_arr.nbytes} bytes")

In [6]:
# easiest way to create array is by a list
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)
#int64 - integer
arr2=np.array([1,2,3,4,5,"yash"])# converts everything into string
print(arr2,type(arr2),arr2.dtype,arr2.shape)
#U21 means strings stored in unicode format 
#6 dimensions(n x m) array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape,arr2D.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'yash'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int64


In [7]:
#creating arrays from scratch
arr=np.zeros((2,3),dtype="int64")#2x3 array with zero prefilled
print(arr,arr.shape,arr.dtype)

arr=np.ones((2,3))#2x3 array with zero prefilled
print(arr,arr.shape,arr.dtype)
arr=np.full((3,4),100)
print(arr,arr.shape)

arr=np.eye(3)#identity matrix( sq matrix of (3))
print(arr,arr.shape)

arr=np.arange(0,10,2) #just like range function in list
print(arr,arr.shape)

arr6=np.linspace(0,100,3)#evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3) int64
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  0.  50. 100.] (3,)


In [20]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)#dimension
print(arr.size)#total elements
print(arr.dtype)#data type
print(arr.ndim)#2D

float_arr=arr.astype(np.float64)
print(float_arr)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [25]:
#operation on arrays
arr=np.array([[1,2,3],[4,5,6]])
reshape=arr.reshape((3,2))
print(reshape)
flattened=arr.flatten()
print(flattened,flattened.shape)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6] (6,)


In [29]:
#indexing
arr=np.array([1,2,3,4,5])
print(arr[0])#1
print(arr[3])

1
4


In [36]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1],arr[1][1])

5 5


In [38]:
#fancy indexing
arr=np.array([1,2,3,4,5,6])
idx=[0,1,3]
print(arr[idx])

[1 2 4]


In [43]:
#boolean indexing
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[4 5 6]
[2 4 6]
[1 3 5]


In [52]:
#slicing
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])
print(arr[:4])
print(arr[1:])
print(arr[::2])

[2 3 4 5]
[1 2 3 4]
[2 3 4 5 6]
[1 3 5]


In [62]:
#copy Vs view
lst=[1,2,3,4,5]
sub_lst=lst[1:4]#copy created
print(sub_lst)
sub_lst[0]=200
print(sub_lst)
print(lst)

arr=np.array([1,2,3,4,5])
sub_arr=arr[1:4]# sub part of original array
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

#we want to create a copy in array
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:4].copy() # copy created of the view
print("copy : ",sub_arr)
print(arr)

[2, 3, 4]
[200, 3, 4]
[1, 2, 3, 4, 5]
[2 3 4]
[200   3   4]
[  1 200   3   4   5]
copy :  [200   3   4]
[1 2 3 4 5]


In [66]:
arr1=np.array([3+4j])
arr2=np.array([4-2j])
print(arr1-arr2,arr1.dtype)
arr3=np.array([2,"yash",{1,2,3,4}])
print(arr3,arr3.dtype)

[-1.+6.j] complex128
[2 'yash' {1, 2, 3, 4}] object


In [3]:
#multi dimensional array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [10]:
#3D array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2x2x3
print(arr3D,arr3D.shape)
print(arr3D[0,1,1])
#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,:,0])#first column



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[ 1  3  5]
 [ 7  9 11]]


In [13]:
#vectorization
arr=np.array([1,2,3,4,5])
print(arr**2)
print(arr+2)
arr2=np.array([9,8,7,6,5])
print(arr+arr2)

[ 1  4  9 16 25]
[3 4 5 6 7]
[10 10 10 10 10]


In [17]:
#broadcasting
arr=np.array([1,2,3,4,5])
arr2=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(arr+arr2)

[[[ 2  4  6  8 10]
  [ 2  4  6  8 10]]

 [[ 2  4  6  8 10]
  [ 2  4  6  8 10]]]


In [24]:
#vector normalization
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
normalized_arr=(arr-mean)/std_dev
print(mean)
print(std_dev)
print(np.sqrt(5/4))
print(normalized_arr,np.std(normalized_arr))

2.5
1.118033988749895
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]] 1.0


In [34]:
# numpy math functions
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr),np.max(arr))
print(np.argmin(arr),np.argmax(arr))#gives index of min, max
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))
#do it again in notebook

15
120
1 5
0 4
3.0
1.4142135623730951
3.0
2.0


In [38]:
#power fxn
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [42]:
#log function
arr=np.array([1,2,3,4,5])
print(np.log(arr))#natural log
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [50]:
#rounding
print(np.round(8.5))
print(np.ceil(8.5))
print(np.floor(8.5))
print(np.trunc(8.5))

#unique
arr=np.array([1,-2,3,4,-5,5,3,2])
print(np.unique(arr))
print(np.sort(arr))
print(np.unique(arr))


8.0
9.0
8.0
8.0
[1 2 3 4 5]
[1 2 2 3 3 4 5 5]
