In [1]:
import numpy as np
import time

In [2]:
a=[1,2,3,4,5]
print(type(a))

<class 'list'>


In [3]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#compare execution performance
# size=1_000_000
# py_list=list(range(size))
# start=time.time()
# sq_list=[x**2 for x in py_list]
# end=time.time()
# print(f"python list time ={end-start} seconds")
# np_arr=np.array(py_list)
# start=time.time()
# sq_arr=np_arr**2 # vectorization
# end=time.time()
# print(f"nimpy array time ={end-start} seconds")


In [5]:
#memory comparison
# import sys
# print(f"python list size = {sys.getsizeof(py_list)*len(py_list)} bytes")
# print(f"numpy array size ={np_arr.nbytes} bytes")

In [6]:
# easiest way to create array is by a list
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)
#int64 - integer
arr2=np.array([1,2,3,4,5,"yash"])# converts everything into string
print(arr2,type(arr2),arr2.dtype,arr2.shape)
#U21 means strings stored in unicode format 
#6 dimensions(n x m) array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape,arr2D.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'yash'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int64


In [7]:
#creating arrays from scratch
arr=np.zeros((2,3),dtype="int64")#2x3 array with zero prefilled
print(arr,arr.shape,arr.dtype)

arr=np.ones((2,3))#2x3 array with zero prefilled
print(arr,arr.shape,arr.dtype)
arr=np.full((3,4),100)
print(arr,arr.shape)

arr=np.eye(3)#identity matrix( sq matrix of (3))
print(arr,arr.shape)

arr=np.arange(0,10,2) #just like range function in list
print(arr,arr.shape)

arr6=np.linspace(0,100,3)#evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3) int64
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  0.  50. 100.] (3,)


In [13]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)#dimension
print(arr.size)#total elements
print(arr.dtype)#data type
print(arr.ndim)#2D

float_arr=arr.astype(np.float64)
print(float_arr,float_arr)

(3, 3)
9
int64
2
